# This is a basic workflow to help you get started with Actions

name: Deploy to VPS

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create executable jar
      run: ./gradlew bootJar
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.0.1
      with:
        key: ${{ secrets.WALLE_SSH_KEY_FOR_DEPLOYMENT }}
        known_hosts: ${{ secrets.WALLE_KNOWNHOST }}
      
    # Upload to VPS
    - name: Ensure directory is created
      run: ssh root@${{ secrets.WALLE_VPS_IP }} "mkdir /opt/solipool/ -p"
    
    - name: Upload jar to VPS
      run: scp build/libs/solipool.jar root@${{ secrets.WALLE_VPS_IP }}:/opt/solipool/solipool.jar

    - name: Copy systemd files
      run: scp deployment/solipool.service root@${{ secrets.WALLE_VPS_IP }}:/etc/systemd/system/solipool.service

    - name: Reload systemd daemon
      run: ssh root@${{ secrets.WALLE_VPS_IP }} "systemctl daemon-reload"

    - name: Reload service
      run: ssh root@${{ secrets.WALLE_VPS_IP }} "systemctl restart solipool.service"
